### ISSUE TITLE
Parallel HDF5 output for multi-dim variables

### ISSUE THREAD

**Issue by jpmeng** [gihanmudalige/OPS#69]
It appears that the ops_fetch_block_hdf5_file call fails to correctly export a ops_dat object with multi-dimension in the parallel computing mode. On the other hand, It appears that this call tend not to overwrite the data in an existing h5 file.

**Comment by gihanmudalige** [comment]
I see that you have a branch with a fix in https://github.com/gihanmudalige/OPS/tree/MultiDimVariableHDF5OutputFix

Is this a fix for this issue ?

**Comment by jpmeng** [comment]
Gihan, yes it is. Just back from lunch. Jianping

**Comment by jpmeng** [comment]
Done. Just please check other routines, I just looked at the void ops_fetch_dat_hdf5_file(ops_dat dat, char const *file_name) routine, not sure if there will be side effects on other routines.

**Comment by jpmeng** [comment]
Gihan, 

I can see there will be inconsistency with other routines. 

As you may have found, the issue is mainly caused by 
gbl_size[1] = gbl_size[1] * dat->dim
but
size[0]=size[0]*dat->dim in the original code, which confused the HD5Write routine for 2D problems. 

In my case , I actually find that growing the gbl_size[1] and size[1] by dat->dim, will make the HD5Write work 
but the index order of data in the outputted HDF5 file are in chaos. I didn’t manage to get a right order in post-processing. 
It appears that growing gbl_size[0] and size[0] by dat->dim is more clear and consistent. If this is the case, then we need to 
change other routines, mainly for the 2D case, I think. 

Cheers,

Jianping

**Comment by gihanmudalige** [comment]
The fix in your MultiDimVariableHDF5OutputFix branch was merged to master. I believe this issue is now solved
